.TH WS 1
.SH NAME
ws \- sort words in multiple files or entered at prompt
.SH SYNOPSIS
.B ws
[\fIOPTIONS\fR]
[\fB\-c\fR \fINUM_WORDS\fR]
[\fIFILE\fR...]
.SH DESCRIPTION
.TP
\fBws\fR sorts words in the named input files or entered at a prompt. If no filename is provided, then the user is prompted to enter no more than 100 words each no longer than 256 characters. The user will enter \fICntrl+D\fR when done. If filenames are provided their names are also expected to be no more than 256 characters. In either the case of file input or stdin input, trailing punctuation is considered to be part of the word.  
.PP
The most recently entered ordering flag will take precedence. Any of the printng options can be combined with the sorting options. 
.SH OPTIONS
.TP
.BR \-h
Output a usage message and then exit.
.TP
.B Printing Options
.TP
.BR \-c " " \fINUM_WORDS\fR
Set the number of sorted words to display. \fINUM_WORDS\fR is required with the -c option.
.TP
.BR \-u
Print the list of words, omitting any that are duplicated like uniq -u in UNIX.
.TP
.BR \-r
Print the list of words in sorted in reverse order descending. Multiple -r's cancel out.
.TP
.B Sort Order Options
.TP
.BR \-n
Print the list of words sorted as if they were numbers. Non-numerical words will be considered 0. For example: 1,2,one will be sorted as one,1,2.
.TP
.BR \-l
Print the list of words sorted by lengths. 
.TP
.BR \-s
Print the list of words sorted by their Scrabble scores. Non-alphabet characters will not count towards the Scrabble score.
.TP
.BR \-a
Print the list of words sorted lexicographically ascending. This is the default sort order.
.SH EXAMPLES
.TP
\fBws\fR \fI-rn file1\fR prints the words in file1 in reverse order as if they were numbers. Any word that is not a number is considered zero.
.TP
\fBws\fR \fI-rr file1\fR prints the words in file1 in ascending lexicographical order.
.TP
\fBws\fR \fI-rlns -c 3 file1\fR prints the words in  file1 with the lowest 3 Scrabble scores in ascending score order.
.SH AUTHOR
.TP
Written by Glenn Hazelwood.
.SH SEE ALSO
.TP
.B Regular Manual Pages
sort(1), wc(1), uniq(1)
